Traceback (most recent call last):
  File "main.py", line 54, in <module>
    game.run()
  File "main.py", line 24, in run
    self.clock.tick(60)
KeyboardInterrupt
[PYI-30888:ERROR] Failed to execute script 'main' due to unhandled exception!
